# -*- coding: utf-8 -*-
"""movie reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKAL1YpE66NSWJ7WtBaUNlNBuFJOQMh8
"""

# Import necessary libraries
import numpy as np
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding
from tensorflow.keras.preprocessing import sequence


# We're using the IMDB dataset for demonstration; this dataset is preloaded with Keras
(top_train_data, top_train_labels), (top_test_data, top_test_labels) = imdb.load_data(num_words=10000)


max_review_length = 500
train_data = sequence.pad_sequences(top_train_data, maxlen=max_review_length)
test_data = sequence.pad_sequences(top_test_data, maxlen=max_review_length)

# Build the LSTM model
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=64, input_length=max_review_length))
model.add(LSTM(units=50))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

# Train the model
model.fit(train_data, top_train_labels, epochs=3, batch_size=64)


scores = model.evaluate(test_data, top_test_labels)
print(f"Accuracy: {scores[1]*100}%")